package com.music.phoenix.model;

public enum GenreType {
    ALTERNATIVE, ANIME, ASIAN, BLUES, CHILDREN, CLASSICAL, COMEDY, COUNTRY, DANCE, DISNEY, ELECTRONIC, ENKA, FOLK,
    RAP, HOLIDAY, INDUSTRIAL, GOSPEL, INSTRUMENTAL, JAZZ, KARAOKE, LATIN, METAL, NEW_AGE, OPERA, POP, SOUL,
    SOUNDTRACK, VOCAL
}
